Fixes fail when parameter file missing
root@91107bedf108:/opt/cloudmapper# python cloudmapper.py report --account st
* Getting resource counts
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/opt/cloudmapper/commands/report.py", line 476, in run
    report(accounts, config, args)
  File "/opt/cloudmapper/commands/report.py", line 102, in report
    account, args.stats_all_resources
  File "/opt/cloudmapper/shared/common.py", line 306, in get_account_stats
    )["LocationConstraint"]
TypeError: 'NoneType' object is not subscriptable